.github/workflows/on_push.yml
clickhouse_connect/cc_sqlalchemy/datatypes/base.py
clickhouse_connect/cc_sqlalchemy/ddl/tableengine.py
clickhouse_connect/datatypes/__init__.py
clickhouse_connect/datatypes/base.py
clickhouse_connect/datatypes/network.py
clickhouse_connect/datatypes/registry.py
clickhouse_connect/dbapi/cursor.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/httpclient.py
pylintrc
tests/integration_tests/test_client.py
tests/unit_tests/test_sqlalchemy/test_ddl.py

Fix misuse of root logger, stop removing newlines from SQL, pin PyLint

Logging cleanup

---

README.md

- Making these Python codes highlighting.

Add Python code highlighting

---

CHANGELOG.md
clickhouse_connect/datatypes/temporal.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/httputil.py
clickhouse_connect/driver/query.py
tests/integration_tests/test_pandas.py
tests/integration_tests/test_params.py
tests/integration_tests/test_proxy.py

bug fixes for v0.5.19

---

.github/workflows/on_push.yml
.github/workflows/publish.yml
CHANGELOG.md
clickhouse_connect/driver/ctypes.py
clickhouse_connect/json_impl.py
pyproject.toml
tests/test_requirements.txt

Python 3.12 update, minor improvements

Release 0 6 15

---

clickhouse_connect/driver/transform.py

Fix the small logging message typo

fix the small logging message typo

---

.github/workflows/on_push.yml
CHANGELOG.md
clickhouse_connect/driver/npquery.py
clickhouse_connect/driver/query.py
pylintrc
tests/integration_tests/test_external_data.py
tests/integration_tests/test_native.py
tests/integration_tests/test_timezones.py

Minor bug fixes, attempted `query_df` performance improvement

Improve query_df, update pylint

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/transform.py
clickhouse_connect/tools/testing.py
tests/integration_tests/test_native.py

fix issue with multibyte UTF8 column names

---

clickhouse_connect/driver/common.py
clickhouse_connect/driver/dataconv.py
tests/integration_tests/conftest.py
tests/integration_tests/test_native.py
tests/integration_tests/test_sqlalchemy/conftest.py
tests/integration_tests/test_sqlalchemy/test_basics.py
tests/integration_tests/test_sqlalchemy/test_inserts.py

Skips the deprecated experimental object/JSON tests

Skip json tests

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/client.py

Bump version and changelog for release

Housekeeping for 0.7.4 release

---

CHANGELOG.md
clickhouse_connect/driver/query.py
tests/integration_tests/conftest.py
tests/integration_tests/test_params.py

Fix client side binding with numeric types

Client side binding fix

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/cc_sqlalchemy/datatypes/sqltypes.py
clickhouse_connect/cc_sqlalchemy/ddl/tableengine.py
clickhouse_connect/datatypes/registry.py
clickhouse_connect/driver/query.py
tests/integration_tests/test_sqlalchemy/test_reflect.py

Fixes SQLAlchemy Point reflection, closes #332 

Fix sqlalchemy Point

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/context.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/npquery.py
clickhouse_connect/driver/query.py
clickhouse_connect/driver/tzutil.py
setup.py
tests/conftest.py
tests/integration_tests/conftest.py
tests/integration_tests/test_pandas.py
tests/integration_tests/test_timezones.py

Updates client timezone handling to avoid inconsistent results due to Daylight Savings Time

Client timezone update

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/__init__.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/httputil.py
clickhouse_connect/driver/npquery.py
pyproject.toml
tests/integration_tests/test_client.py
tests/test_requirements.txt

Add show_clickhouse_errors parameter, various other tweaks

---

.github/workflows/publish.yml
CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/npquery.py

Small cleanup for empty pandas series

Release 0 7 10

---

.github/workflows/publish.yml
CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/npquery.py

Tweak public artificacts

---

examples/run_async.py

Adds a simple example of how to convert queries to async, using a single (thread safe) client

Add an example of how to run async

---

.github/workflows/clickhouse_ci.yml
.github/workflows/on_push.yml
.github/workflows/publish.yml
docker-compose.yml

Test workflow updates

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/datatypes/numeric.py
clickhouse_connect/driver/common.py
tests/integration_tests/test_inserts.py

Fixes some type conversions.  Closes #414

Move type conversion to specific datatypes

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/httputil.py
clickhouse_connect/driver/transform.py

Fix chunked streaming and wait_end_of_query bug

---

.github/workflows/on_push.yml
CHANGELOG.md
clickhouse_connect/datatypes/base.py
clickhouse_connect/datatypes/container.py
clickhouse_connect/datatypes/dynamic.py
clickhouse_connect/datatypes/geometric.py
clickhouse_connect/datatypes/network.py
clickhouse_connect/datatypes/numeric.py
clickhouse_connect/datatypes/special.py
clickhouse_connect/datatypes/string.py
clickhouse_connect/datatypes/temporal.py
clickhouse_connect/driver/client.py
tests/integration_tests/test_dynamic.py
tests/unit_tests/test_driver/test_native_read.py

Various fixes for Variant/Dynamic/JSON serialization.  Closes #441 

Dynamic type serialization fixes

---

README.md

Update README.md doc link

---

CHANGELOG.md

update changelog for v0.8.18 release
