clickhouse_connect/datatypes/container.py
clickhouse_connect/driver/common.py
clickhouse_connect/driver/httpclient.py
tests/integration_tests/test_client.py

Main fix is to the implicit conversion of Decimals to floats or ints when populating a ClickHouse column of Float/Int with Python decimals

Deprecation fix

---

clickhouse_connect/driver/client.py
clickhouse_connect/driver/httpadapter.py
clickhouse_connect/driver/httpclient.py

I believe this fixes the timeout issues reported in dbt-clickhouse.  Silly me for thinking that a requests keep alive connection would also add keep alive to the TCP socket.  See the discussion below 
https://www.finbourne.com/blog/the-mysterious-hanging-client-tcp-keep-alives
https://github.com/psf/requests/issues/3353

Add socket options for TCP keep alive to HTTP adapter

---

README.md

Since the README is serving as the only real source of documentation for the project you should include the pip installation instructions and optionally a link to PyPi.
I had members of my team run into issues with the `setup.py` installation because they didn't even know the project was available through PyPi. This is the easiest route for installation and is standard to include in documentation for Python projects.

Include pip installation

---

.github/workflows/on_push.yml
clickhouse_connect/cc_sqlalchemy/ddl/custom.py
clickhouse_connect/cc_sqlalchemy/sql/__init__.py
clickhouse_connect/cc_sqlalchemy/sql/ddlcompiler.py
clickhouse_connect/cc_sqlalchemy/sql/preparer.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/query.py
setup.py
tests/integration_tests/test_client.py
tests/integration_tests/test_data_libraries.py
tests/test_requirements.txt

-- Always backtick quote identifiers in SQLAlchemy and client insert statements
-- Clean up push workflow to not require pip install -e (this makes tests and lint checking possible without setting an explicit version in setup.py, which we only do on release
-- Minor refactoring for inserts to cleanly support direct inserts of arrow tables

Arrow inserts

---

clickhouse_connect/driver/httpclient.py

`SELECT name, value, changed, description, type, readonly FROM system.settings` do not return `wait_end_of_query` setting, so it added in `HttpClient.valid_transport_settings`
fixes error handling for errors during queries that use `ON CLUSTER` (check https://github.com/ClickHouse/ClickHouse/issues/15124 for more details)
fixes https://github.com/ClickHouse/dbt-clickhouse/issues/83

added wait_end_of_query in valid_transport_settings

---

.github/workflows/on_push.yml
tests/integration_tests/conftest.py
tests/integration_tests/test_sqlalchemy/test_ddl.py

Append the unix time in millis at the end of the test DB name to be in line with JS and Go clients for cleanup purposes.

Append unixtime millis to the test db name when using Cloud

---

clickhouse_connect/cc_sqlalchemy/datatypes/base.py

Hi @genzgd
We use ClickHouse in apache/superset. Before `clickhouse-connect` we used `clickhouse-sqlalchemy` driver.
When we migrated to `clickhouse-connect` we noticed that ClickHouse type name is changed from UPPER to Pascal case.
All our superset datasets columns have UPPER case types in superset DB and we have the next error:
> error: "Unrecognized ClickHouse type base: UINT64 name: UINT64"
We need to write a flexible logic to ignore case of type name.
I prepare `CaseInsensitiveDict` class in order to make all item keys lowercase and get it also by lowercase key.
This PR resolves our problem of migrating from `clickhouse-sqlalchemy` to `clickhouse-connect`

Use CaseInsensitiveDict for sqla_type_map

---

CHANGELOG.md

Update CHANGELOG.md to align the format with clickhouse-go and clickhouse-js

update Changelog to follow a common pattern

---

clickhouse_connect/driver/query.py
tests/unit_tests/test_driver/test_query.py

"with" statement with `QueryResult` is currently broken. You can reproduce the issue with this:
```python
from clickhouse_connect.driver.query import QueryResult
with QueryResult() as query_result:
print('query_result =', query_result)
```
results in:
```text
query_result = None
```
`query_result` should not be `None` here. It breaks "with" context for queries (which is the recommended way now). The problem is that [clickhouse_connect.driver.query.QueryResult.__enter__](https://github.com/ClickHouse/clickhouse-connect/blob/097415b998133db143ae63fc541a7e506e6ff357/clickhouse_connect/driver/query.py#L241) does not return anything. So from the documentation, the [query streaming example](https://clickhouse.com/docs/en/integrations/language-clients/python/advanced#query-streaming) simply does …

Fix QueryResult "with" statement context

---

CHANGELOG.md
clickhouse_connect/driver/npquery.py
tests/integration_tests/test_pandas.py

Return empty dataframe instead of list for query_df result with no records.  https://github.com/ClickHouse/clickhouse-connect/issues/118

Return empty df instead of list

---

clickhouse_connect/datatypes/temporal.py
tests/integration_tests/test_numpy.py

Improve error message for invalid numpy/Pandas DateTime64 types.  https://github.com/ClickHouse/clickhouse-connect/issues/126

Better error message for invalid numpy DateTime64 types

---

clickhouse_connect/driver/client.py

If connection settings aren't available/exposed, any connection fails after initial settings select
```sql
SELECT name, value, readonly as readonly FROM system.settings
```
not relevant

fix key error in connection with no available settings from server

---

CHANGELOG.md
clickhouse_connect/driver/query.py
tests/unit_tests/test_driver/test_parameters.py

Fixes #159 - quoting and escaping string literals inside lists
The PR could be completed with more tests (e.g. tuples, dicts, etc) and more scoped tests (e.g. unit testing `format_str` and `escape_str` themselves). Feel free to take over the PR and do it.

Fixes #159 - quoting and escaping string literals inside lists

---

clickhouse_connect/common.py
clickhouse_connect/driver/httpclient.py

An optional parameter added to HTTP Client class to allow user to decide how long they want the database error messages to be when returned. Fixes this [issue](https://github.com/ClickHouse/clickhouse-connect/issues/198)

Optional max_error_chars parameter added to HTTP Client class 

---

clickhouse_connect/common.py
clickhouse_connect/entry_points.py
setup.py

pkg_resources is in the process of being deprecated in favor of
importlib.metadata and importlib.resources
importlib.metadata has been available in the standard library since 3.8
And as of 3.10 the importlib.metadata API is no longer provisional
In order to support Python version older than 3.10, the
importlib_metadata backport is used instead of the actual
importlib.metadata API.
(NOTE: There was no explicit install_require entry that needed removing
in setup.py for the setuptools package which provides the pkg_resources
module. It seems that it was merely assumed that setuptools is always
present, which is actually not the case.)

refactor: pkg_resources -> importlib.metadata

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/datatypes/container.py
tests/integration_tests/test_native.py

Adds support for Object(Nullable('json')) type

Add support for Object(Nullable('json')) type

---

clickhouse_connect/datatypes/container.py

Fixes this bug: https://github.com/ClickHouse/clickhouse-connect/issues/239
When you have an empty map that has a type of nests maps, and IndexError is raise; this fixes that issue. 
Example: 
```python
client.query("select Cast(([],[]), 'Map(String, Map(String, String))')")
```

fix: Empty nests raising out of IndexError.

---

setup.py

PEP 561 introduced the idea of a "py.typed" file that when present,
denotes a package as having type hints. Including this file into
ClickHouse-Connect means that users of it can use the type hints
provided and statically analyse their own code.
PEP 561 source:
https://peps.python.org/pep-0561/#packaging-type-information
I tested this with the following:
```
$ python3.11 -m build | grep py.typed
...
copying clickhouse_connect/py.typed -> clickhouse-connect-0.6.12/clickhouse_connect
copying clickhouse_connect/py.typed -> build/lib.macosx-12-arm64-cpython-311/clickhouse_connect
...
copying build/lib.macosx-12-arm64-cpython-311/clickhouse_connect/py.typed -> build/bdist.macosx-12-arm64/wheel/clickhouse_connect
adding 'clickhouse_connect/py.typed'
$ tar tzf …
```

Add py.typed file (PEP 561)

---

clickhouse_connect/__init__.py
clickhouse_connect/driver/__init__.py

`get_client` is the main entrypoint to getting a Client instance. Currently, it
is merely a wrapper for `create_client`, taking only `**kwargs`. Due to the
wrapping and use of `**kwargs`, all type hints are lost.
To improve the situation without breaking existing code, `get_client` is
redefined as a simple alias of `create_client`. Additionally, `create_client` is
altered to force the use of keyword arguments according to the PEP 3102 [0]
asterisk. This combination of changes improves the usability of the `get_client`
function while preserving all existing functionality.
[0] - https://peps.python.org/pep-3102/

Alias get_client directly instead of via a function

---

CHANGELOG.md
clickhouse_connect/cc_sqlalchemy/datatypes/sqltypes.py

Fixes https://github.com/ClickHouse/clickhouse-connect/issues/278 by adding Nothing datatype for SQLAlchemy

Add missing Nothing datatype for SQLAlchemy

---

CHANGELOG.md
clickhouse_connect/driver/npquery.py

Pandas 2.1.0 introduced a FutureWarning when concatenating empty DataFrames (or those with all-NA entries). 
```
.../clickhouse_connect/driver/npquery.py:99: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
self._df_result = pd.concat(pieces, ignore_index=True)
```
This PR filters empty pieces before concatenation is performed; it does not remove empty pieces from the data frame stream.

Fix Pandas Concatenation Warning

---

clickhouse_connect/driver/client.py

Despite a type hint of `str`, the default parameter for these methods is `None`. This makes type analyzers sad.
To fix this, hint the type as `Optional[str]` to match reality.
It's not correct to say that `query` is a required, non-None type due to the possibility of a QueryContext with an existing query. Therefore, this is the more correct change.

Correct typing of Client.query*(query)

---

.github/workflows/clickhouse_ci.yml
.github/workflows/on_push.yml
.github/workflows/publish.yml
CHANGELOG.md
LICENSE
clickhouse_connect/__version__.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/tools.py
setup.py
tests/integration_tests/conftest.py
tests/integration_tests/test_tools.py

Small bug fix for insert_file, cleanup github actions

Release 0 7 1

---

CHANGELOG.md
clickhouse_connect/dbapi/cursor.py
tests/integration_tests/test_sqlalchemy/test_basics.py

Add summary field to Cursor object to retrieve the result of 'X-Clickhouse-Summary' header
Fixes https://github.com/ClickHouse/clickhouse-connect/issues/316

Add summary field to the Cursor object

---

clickhouse_connect/driver/client.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/query.py
tests/integration_tests/test_arrow.py

Adds a `query_arrow_stream` call that returns a generator that returns pyarrow.Table objects.
Issue #155

Add query_arrow_stream

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/external.py
tests/integration_tests/test_external_data.py

Before this patch, the `ExternalData` / `ExternalFile` APIs would not create an empty table when `data=b''` was being passed, because `data` would be checked for truthiness. This PR fixes this bug by using `data is not None` checks instead.
Added an integration test to cover this case.

fix(external-data): allow empty data external data

---

clickhouse_connect/driver/client.py

Fixed error on warning message when indicating that a timezone may create nonsensical timezones.

added missing parameter to tzname

---

clickhouse_connect/datatypes/numeric.py
tests/integration_tests/test_inserts.py

Issue raised in [this slack discussion](https://clickhousedb.slack.com/archives/CU478UEQZ/p1716398118092689)
When converting a float value to a decimal field, values like `0.1234567` end up being `0.1234566` in clickhouse.
There seem to be two different ways of fixing this:
- casting the float as a string before passing it to the `Decimal` constructor.
- not casting the float, but rounding the conversion instead of truncating it
This PR uses string casting to fix the issue, as most examples of decimal usages pass values represented as strings to the `Decimal` constructor.

Fix precision loss in Float to Decimal conversion

---

setup.py

Fix for: https://github.com/ClickHouse/clickhouse-connect/issues/360
Not all versions of tzlocal support get_localzone_name()
clickhouse_connect/driver/tzutil.py
https://github.com/ClickHouse/clickhouse-connect/blob/bdad0e389d7ec46f109eccc825bc088fd2a78b6b/clickhouse_connect/driver/tzutil.py#L29
`local_name = tzlocal.get_localzone_name()`
This function is only available in tzlocal 4.0.0 and up.
See: 
https://github.com/regebro/tzlocal/blob/master/CHANGES.txt
4.0b2 (2021-09-26)
------------------
- Big refactor; Implemented get_localzone_name() functions.
- Adding a Windows OS environment variable 'TZ' will allow an override for
setting the timezone (also see 4.0b3).

Added minimum version for tzlocal

---

clickhouse_connect/driver/httpclient.py

Hi,
The issue is the HTTPDriver return the Clickhouse server sensitive detail: **IP & Port** in the error exception.
Example:
```
Error: HTTPDriver for http://10.15.27.43:8123 returned response code 404)
Code: 60. DB::Exception: Table test.users_1 does not exist. Maybe you meant test.users? (UNKNOWN_TABLE) (version 23.12.3.40 (official build))
```
Expected:
```
Error: HTTPDriver returned response code 404)
Code: 60. DB::Exception: Table test.users_1 does not exist. Maybe you meant test.users?. (UNKNOWN_TABLE) (version 23.12.3.40 (official build))
```
This will lead to an issue that the downstream application using this Clickhouse Connect driver, 
They will return the details to the client side and the UI will show the **IP & Port** then the hacker may use this to attack. 
We might run …

Sercurity issue: remove clickhouse server ip & port in the exception

---

clickhouse_connect/datatypes/base.py
clickhouse_connect/datatypes/network.py
clickhouse_connect/datatypes/numeric.py
clickhouse_connect/datatypes/string.py
clickhouse_connect/datatypes/temporal.py
clickhouse_connect/driver/common.py
clickhouse_connect/driver/context.py
clickhouse_connect/driver/insert.py

Previously if you inserted a NULL into a column that isn't Nullable, the error you got was 
> Unable to create Python array. This is usually caused by trying to insert None values into a ClickHouse column that is not Nullable
which is unhelpful for working out *which* column is the problem. I've modified that error path so it can include the column name in the error, like so:
> Failed to write column 'bus_voltage': Unable to create Python array. This is usually caused by trying to insert None values into a ClickHouse column that is not Nullable
I felt like this was a pretty small change so I didn't add tests or file an issue, I hope that's okay.

Include the column name in the error message for an unexpected NULL

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/httputil.py

Clean up some code for http buffer handling.  May fix #401

Clean up http buffer

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/httputil.py
clickhouse_connect/driver/query.py
tests/integration_tests/test_arrow.py

Add built in Arrow compression for inserts.  Closes #267.
One more http buffer tweak.  May close #403.

Arrow compression plus another http buffer tweak

---

CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/driver/__init__.py
clickhouse_connect/driver/asyncclient.py

Adds an executor_threads parameter to `get_async_client`.  Closes #407

Add executor_threads parameter to async client

---

.github/workflows/on_push.yml
CHANGELOG.md
clickhouse_connect/__version__.py
clickhouse_connect/datatypes/dynamic.py
clickhouse_connect/driver/buffer.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/transform.py
clickhouse_connect/driver/types.py
clickhouse_connect/driverc/buffer.pyx
tests/integration_tests/test_dynamic.py

Update for experimental JSON support in ClickHouse 24.10+.  Closes #436 

Update experimental JSON support

---

CHANGELOG.md
clickhouse_connect/datatypes/temporal.py

Support of ISO8601 datetime string is added for columns with `DateTime64` type.
Now it is possible to pass timestamps like that:
And it is successfully inserted into clickhouse:

Add support of ISO8601 timestamp strings for columns with `DateTime64` type

---

clickhouse_connect/driver/httpclient.py

0.8.12 introduced a new `access_token` parameter to the `clickhouse_connect.driver.HttpClient` class that is marked as `Optional[str]` but has no default value. It is properly defaulted in `create_client`, but if you directly create an instance of `HttpClient` in 0.8.12, it fails due to the missing new argument
This PR adds a `None` default value to the `HttpClient` `__init__` to mirror `create_client` and fix the issue

fix: add default value for access token in HttpClient init

---

CONTRIBUTING.md

Small PR - Commit d113091d4c14cfd90ce39ee33e6fe7d44dfbe400 moved `test_tls.py`. This PR adjusts sources to changes. 

Update `test_tls.py` reference

---

clickhouse_connect/driver/asyncclient.py
examples/run_async.py
tests/integration_tests/conftest.py
tests/integration_tests/test_session_id.py

It's known that ThreadPoolExecutor doesn't deallocate memory without .shutdown being called. Python's GC doesn't stop running thread pools, so the code like
```python
while True:
client = await get_async_client(...)
...
client.close()
```
will be leaking memory since each new AsyncClient instance will have a new executor.
Closes https://github.com/ClickHouse/clickhouse-connect/issues/424

Fix memory leak in AsyncClient

---

.docker/clickhouse/single_node/config.xml
.docker/clickhouse/single_node_tls/config.xml
docker-compose.yml

Add environment variable to allow empty string password for default user

Fix CI tests with default user

---

clickhouse_connect/driver/binding.py

Replace manual ; removal loop with rstrip method
Replaced while loop with endswith(';') check and string slicing with rstrip(";") call.
Eliminated redundant code by using a built-in method for trailing character removal.
Code is more concise and explicitly conveys intent.
`rstrip` is more efficient than sequential checks and slicing in a loop.

Replace removal of ; in the loop line with rstrip

---

.docker/clickhouse/single_node/config.xml
.docker/clickhouse/single_node/docker_related_config.xml
.docker/clickhouse/single_node_tls/Dockerfile
.docker/clickhouse/single_node_tls/config.xml
.docker/clickhouse/single_node_tls/docker_related_config.xml
clickhouse_connect/driver/client.py
docker-compose.yml
tests/integration_tests/test_dynamic.py

Trying to fix docker issues with 25.1 docker image

Docker test fixes

---

clickhouse_connect/driver/__init__.py

The parameters `host` and `username` of `create_client` actually do accept None values, as demonstrated by their default values being `None` and the docstring explaining default behavior when not-set.
Correcting these types (by marking as Optional) allows users using `dsn` or default behavior to not see type-checking errors.

Correct typing of create_client(host, username)

---

CHANGELOG.md
clickhouse_connect/driver/asyncclient.py
clickhouse_connect/driver/client.py
clickhouse_connect/driver/context.py
clickhouse_connect/driver/httpclient.py
clickhouse_connect/driver/insert.py
clickhouse_connect/driver/query.py
tests/integration_tests/test_client.py

Changes extra_http_headers to transport_settings for future compatibility (GRPC/Native eventually).  Added the new parameter to insert methods and the async client.

Change extra_http_headers to transport_settings

---

clickhouse_connect/cc_sqlalchemy/dialect.py

When executing raw SQL queries with SQLAlchemy integration in clickhouse-connect, users may encounter ObjectNotExecutableError: Not an executable object: 'EXISTS TABLE ...' error. This happens because SQLAlchemy (especially in versions 1.4+ and 2.0) requires SQL strings to be wrapped with the text() function before execution.
This PR modifies the query execution logic to wrap raw SQL strings with SQLAlchemy's text() function, ensuring compatibility across SQLAlchemy versions 1.3, 1.4, and 2.0.

Fix SQLAlchemy execution error by using text() function

---

tests/integration_tests/test_client.py

Tiny change to ensure the column types are always returned

Ensure types are returned even if there are no rows

---

CHANGELOG.md
clickhouse_connect/dbapi/cursor.py
tests/unit_tests/test_driver/test_cursor.py

This PR fixes some issues with cursor behavior (thanks @celeste-sinead). It updates behavior to be more consistent with [PEP-249](https://peps.python.org/pep-0249/), specifically around [cursor methods](https://peps.python.org/pep-0249/#cursor-methods):
- **Reset cursor location after performing an execute** (previously cursor position was not reset)
- **Fix behavior of `fetchall` to only return rows from the current cursor location** (previously returned all rows regardless of cursor position)
- Fixes logic of `fetchmany` to respect size parameter.
- Adds file specifically for testing cursor behavior.
Note: One aspect still inconsistent with PEP-249 is the default size parameter in the `fetchmany` implementation. Currently it defaults to `-1` which fetches all remaining rows. According …

Fix some issues with cursor behavior

---

CHANGELOG.md
clickhouse_connect/driver/asyncclient.py

Change `AsyncClient.settings` typing to `Optional[Dict[str, Any]]` to accept None inputs.

Add asyncclient settings Optional typing

---

CHANGELOG.md
clickhouse_connect/datatypes/base.py
clickhouse_connect/datatypes/temporal.py
tests/integration_tests/test_pandas.py
tests/integration_tests/test_pandas_compat.py
tests/unit_tests/test_driver/test_temporal.py

This PR:
- Fixes some errors when inserting dataframes of `Time` and `Time64` types.
- Enforce consistent resolution of `datetime64` and `timedelta64` dtypes when using `query_df` regardless of Pandas version
- Wires up a way to leverage additional Pandas 2.x resolutions of "s", "ms", "us" for `datetime64` and `timedelta64` dtypes. Note this PR does not expose that ability to the public API yet, but has put the wiring in place. Some additional work around Pandas version detection and setting the flag to use it will come in a future PR.
- Introduces a Pandas compatibility test file that can be expanded to ensure consistent behavior between 1.x and 2.x
- Improves null and nullable handling for time types, including tests to validate new behaviors
Closes #165 
Closes #524 
Delete items not …

Effort toward pandas 2.x support

---

.github/workflows/on_push.yml
CHANGELOG.md
tests/test_requirements.txt

The PR:
- Pins pandas in test_requirements.py to `pandas>=2.0,<3.0`.
- As this was not previously pinned we were getting whatever the latest version pip grabbed was, which was likely 2.x
- Adds a compatibility test to CI that uses Python 3.11 (the latest version that pandas 1.x officially supports) and ClickHouse server `latest`.

add pandas 1x and 2x testing to ci

---

CHANGELOG.md
clickhouse_connect/datatypes/numeric.py
tests/integration_tests/test_numeric.py

Adds support for [interval](https://clickhouse.com/docs/en/sql-reference/data-types/special-data-types/interval) types.
Closes #391

add special interval type support

---

.github/workflows/on_push.yml

Brings the python ver/chserver ver test matrix up to date. Runs cloud tests against all supported python versions.
Closes #538

update test matrix

---

CHANGELOG.md
clickhouse_connect/datatypes/temporal.py
clickhouse_connect/driver/dataconv.py
clickhouse_connect/driver/tzutil.py
clickhouse_connect/driverc/dataconv.pyx
clickhouse_connect/tools/datagen.py

Replace the use of deprecated `datetime.utcfromtimestamp` with a local implementation. This fixes the Python deprecation warnings. Addresses issue https://github.com/ClickHouse/clickhouse-connect/issues/540
Please let me know if there's anything that I should improve on this PR to make it acceptable for merge. Thank you!

Replace the use of deprecated datetime.utcfromtimestamp

---

CHANGELOG.md
clickhouse_connect/driver/httpclient.py
tests/integration_tests/test_client.py

This makes it possible to set a role for a given query. It's still not possible to set *multiple* roles because the way this is expressed in the protocol is by *repeating* the `role=` query parameter, which this application doesn't know how to do. 
A better full-featured solution would be to add a `role=` kwarg that takes a set of roles and builds the query parameters correctly. That's a lot of work, though, so I wanted to offer this quick/hacky workaround to unblock myself for now.
#549

"role" is a valid transport setting
